### ISSUE TITLE
Deploy the website

### ISSUE THREAD

**Issue by mtuchi** [pycontanzania/admin#1]
#### Description

Deploy the work in progress to a staging server 

#### Tasks
- [ ] Setup `docker-compose` for production
- [ ] Deploy the website under `admin.pycon.or.tz`
- [ ] GitHub action CI\CD
