### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by AvicennaJr** [pycontanzania/admin#8]
#### Description
Add tests to ensure the program is working fine.

#### Tasks

- [ ] Tests for validating credentials
- [ ] Tests for getting speakers List
- [ ] Tests for creating new speaker
- [ ] Tests for deleting a speaker
- [ ] Tests for getting events list
- [ ] Tests for creating new event
- [ ] Tests for deleting an event
